spring:
  application:
    name: activity-service

  profiles:
    active: h2

server:
  port: 8082

logging:
  level:
    org.springframework: INFO
##--server:
#port: 8081
#
#spring:
#  application:
#    name: user-service
#
#  datasource:
#    url: jdbc:postgresql://user-db:5433/userdb
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#logging:
#  level:
#    org.hibernate.SQL: debug

